import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  corePlugins: { preflight: false },
  theme: {
    extend: {
      colors: {
        // Direct Clinical Precision brand tokens
        'primary-deep': 'var(--color-primary-deep, #001D32)',
        'primary-light': 'var(--color-primary-light, #E3EFFF)',
        'steel-teal': 'var(--color-steel-teal, #147D92)',
        'surgical-cyan': 'var(--color-surgical-cyan, #28A7A1)',
        canvas: 'var(--color-canvas, #F7F9FB)',
        'brand-ice': 'var(--color-brand-ice, #EDF4FF)',
        heading: 'var(--color-heading, #102A43)',
        body: 'var(--color-body, #42474D)',
        muted: 'var(--color-muted, #7A90A8)',
        'border-strong': 'var(--color-border-strong, #C2C7CD)',
        focus: 'var(--color-focus, #0EA5E9)',
        'surface-subtle': 'var(--color-surface-subtle, #F8FAFC)',

        // Clinical Precision brand — Deep Medical Navy & Steel Teal
        primary: 'var(--brand)',
        'primary-hover': 'var(--brand-hover)',
        'primary-container': 'var(--brand-soft)',
        'on-primary': 'var(--fg-on-brand)',
        'primary-fixed': '#C8E6FF',
        'primary-fixed-dim': '#A3CBEA',
        secondary: 'var(--secondary)',
        'secondary-container': '#EDF4FF',
        'on-secondary-container': '#00687B',
        tertiary: 'var(--tertiary)',
        'tertiary-container': '#E6FAF8',
        'on-tertiary-container': '#00413E',
        gold: 'var(--fg-warning)',
        'gold-soft': 'var(--color-warning-100)',
        'gold-faint': 'var(--color-warning-100)',
        admin: 'var(--brand)',
        'admin-soft': 'var(--brand-soft)',

        // Status colors with full scales
        success: 'var(--color-success-500)',
        'success-50': 'var(--color-success-50)',
        'success-100': 'var(--color-success-100)',
        'success-200': 'var(--color-success-200)',
        'success-300': 'var(--color-success-300)',
        'success-400': 'var(--color-success-400)',
        'success-500': 'var(--color-success-500)',
        'success-600': 'var(--color-success-600)',
        'success-700': 'var(--color-success-700)',
        'success-800': 'var(--color-success-800)',
        'success-900': 'var(--color-success-900)',

        warning: 'var(--color-warning-500)',
        'warning-50': 'var(--color-warning-50)',
        'warning-100': 'var(--color-warning-100)',
        'warning-200': 'var(--color-warning-200)',
        'warning-300': 'var(--color-warning-300)',
        'warning-400': 'var(--color-warning-400)',
        'warning-500': 'var(--color-warning-500)',
        'warning-600': 'var(--color-warning-600)',
        'warning-700': 'var(--color-warning-700)',
        'warning-800': 'var(--color-warning-800)',
        'warning-900': 'var(--color-warning-900)',

        error: 'var(--color-danger-500)',
        'error-50': 'var(--color-danger-50)',
        'error-100': 'var(--color-danger-100)',
        'error-200': 'var(--color-danger-200)',
        'error-300': 'var(--color-danger-300)',
        'error-400': 'var(--color-danger-400)',
        'error-500': 'var(--color-danger-500)',
        'error-600': 'var(--color-danger-600)',
        'error-700': 'var(--color-danger-700)',
        'error-800': 'var(--color-danger-800)',
        'error-900': 'var(--color-danger-900)',
        'on-error': 'var(--fg-on-brand)',
        'error-container': 'var(--color-danger-100)',

        info: 'var(--color-info-500)',
        'info-50': 'var(--color-info-50)',
        'info-100': 'var(--color-info-100)',
        'info-200': 'var(--color-info-200)',
        'info-300': 'var(--color-info-300)',
        'info-400': 'var(--color-info-400)',
        'info-500': 'var(--color-info-500)',
        'info-600': 'var(--color-info-600)',
        'info-700': 'var(--color-info-700)',
        'info-800': 'var(--color-info-800)',
        'info-900': 'var(--color-info-900)',

        // Surfaces & Text
        surface: 'var(--bg-surface)',
        'surface-dim': '#C1DDFB',
        'surface-bright': 'var(--bg-surface)',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#EDF4FF',
        'surface-container': '#E3EFFF',
        'surface-container-high': '#D8EAFF',
        'surface-container-highest': '#CEE5FF',
        'surface-variant': '#CEE5FF',
        'on-surface': 'var(--fg-body)',
        'on-surface-variant': 'var(--fg-muted)',
        outline: 'var(--fg-subtle)',
        'outline-variant': 'var(--border)',
        'inverse-surface': '#16334A',
        'inverse-on-surface': '#E8F2FF',
        'inverse-primary': '#A3CBEA',
        background: 'var(--bg-app)',
        'on-background': 'var(--fg-heading)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',    // 3px
        sm: 'var(--radius-sm)',    // 4px (Base Radius)
        md: 'var(--radius-md)',    // 6px
        lg: 'var(--radius-lg)',    // 8px (Container Radius)
        xl: 'var(--radius-xl)',    // 12px (Outer Container Radius)
        '2xl': 'var(--radius-2xl)',// 16px
        full: 'var(--radius-pill)',// 9999px
      },
      spacing: {
        'space-1': 'var(--space-1, 4px)',
        'space-2': 'var(--space-2, 8px)',
        'space-3': 'var(--space-3, 12px)',
        'space-4': 'var(--space-4, 16px)',
        'space-5': 'var(--space-5, 20px)',
        'space-6': 'var(--space-6, 24px)',
        'space-7': 'var(--space-7, 28px)',
        'space-8': 'var(--space-8, 32px)',
        'space-10': 'var(--space-10, 40px)',
        'space-12': 'var(--space-12, 48px)',
        'space-16': 'var(--space-16, 64px)',
        'space-20': 'var(--space-20, 80px)',
        'space-24': 'var(--space-24, 96px)',
        'input-sm': '36px',
        'input-md': '40px',
        'input-lg': '48px',
        'gutter': '1.75rem',
      },
      fontFamily: {
        display: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'SFMono-Regular', 'Consolas', 'Liberation Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        display: 'var(--text-display, 48px)',
        h1: 'var(--text-h1, 36px)',
        h2: 'var(--text-h2, 30px)',
        h3: 'var(--text-h3, 24px)',
        h4: 'var(--text-h4, 20px)',
        'body-lg': 'var(--text-body-lg, 18px)',
        'body-sm': 'var(--text-body-sm, 14px)',
        caption: 'var(--text-caption, 12px)',
        '2xs': 'var(--text-2xs)',
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        md: 'var(--text-md)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
      },
      boxShadow: {
        none: 'none',
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        glow: 'var(--ring-focus)',
        'glow-error': 'var(--ring-focus-error)',
        'glow-success': 'var(--ring-focus-success)',
        brand: 'var(--shadow-brand)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        base: 'var(--duration-base)',
        slow: 'var(--duration-slow)',
      },
      transitionTimingFunction: {
        'ease-out': 'var(--ease-out)',
        'ease-in-out': 'var(--ease-in-out)',
      },
      borderColor: {
        DEFAULT: 'var(--border)',
        'strong': 'var(--border-strong)',
        'focus': 'var(--border-focus)',
        'error': 'var(--border-error)',
        'success': 'var(--border-success)',
        'warning': 'var(--border-warning)',
      },
      divideColor: {
        DEFAULT: 'var(--border)',
      },
      opacity: {
        'hover': 'var(--state-hover-opacity)',
        'active': 'var(--state-active-opacity)',
        'disabled': 'var(--state-disabled-opacity)',
      },
    },
  },
  plugins: [forms, containerQueries],
}
