/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  corePlugins: { preflight: false },
  theme: {
    extend: {
      colors: {
        primary: 'rgb(var(--wl-primary-rgb) / <alpha-value>)',
        'primary-container': 'var(--wl-primary-soft)',
        'on-primary': 'var(--wl-on-primary)',
        'primary-fixed': 'var(--wl-primary-soft)',
        'primary-fixed-dim': 'var(--wl-primary-faint)',
        secondary: 'rgb(var(--wl-accent-rgb) / <alpha-value>)',
        'secondary-container': 'var(--wl-accent-soft)',
        'on-secondary-container': 'var(--wl-ink-strong)',
        tertiary: 'var(--wl-muted)',
        'tertiary-container': 'var(--wl-surface-soft)',
        'on-tertiary-container': 'var(--wl-ink-strong)',
        error: 'rgb(var(--wl-danger-rgb) / <alpha-value>)',
        'on-error': '#ffffff',
        'error-container': 'var(--wl-danger-soft)',
        surface: 'rgb(var(--wl-surface-rgb) / <alpha-value>)',
        'surface-dim': 'var(--wl-surface-hover)',
        'surface-bright': 'var(--wl-surface)',
        'surface-container-lowest': 'var(--wl-surface)',
        'surface-container-low': 'var(--wl-surface-soft)',
        'surface-container': 'var(--wl-surface-soft)',
        'surface-container-high': 'var(--wl-surface-hover)',
        'surface-container-highest': 'var(--wl-border-strong)',
        'surface-variant': 'var(--wl-surface-soft)',
        'on-surface': 'rgb(var(--wl-ink-strong-rgb) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--wl-ink-soft-rgb) / <alpha-value>)',
        outline: 'var(--wl-muted)',
        'outline-variant': 'var(--wl-line)',
        'inverse-surface': 'var(--clinical-inverse-surface)',
        'inverse-on-surface': 'var(--wl-paper)',
        'inverse-primary': 'var(--clinical-inverse-primary)',
        background: 'rgb(var(--wl-paper-rgb) / <alpha-value>)',
        'on-background': 'rgb(var(--wl-ink-strong-rgb) / <alpha-value>)',
      },
      borderRadius: { DEFAULT: '10px', lg: '12px', xl: '16px', full: '9999px' },
      spacing: {
        'input-sm': '36px',
        'input-md': '44px',
        'input-lg': '52px',
      },
      fontFamily: {
        display: ['Plus Jakarta Sans', 'Sora', 'Alexandria', 'IBM Plex Sans Arabic', 'system-ui', 'sans-serif'],
        body: ['Inter', 'Plus Jakarta Sans', 'IBM Plex Sans Arabic', 'system-ui', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'Inter', 'IBM Plex Sans Arabic', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'IBM Plex Mono', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        sm: '0 1px 2px rgba(15,23,42,0.04)',
        DEFAULT: '0 1px 3px rgba(15,23,42,0.04), 0 4px 12px rgba(15,23,42,0.03)',
        md: '0 4px 6px -1px rgba(15,23,42,0.05), 0 2px 4px -2px rgba(15,23,42,0.05)',
        glow: '0 0 0 3.5px rgba(79, 70, 229, 0.14), 0 2px 8px -2px rgba(79, 70, 229, 0.18)',
        'glow-danger': '0 0 0 3.5px rgba(244, 63, 94, 0.16)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
